{{- if .Values.daemon.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chaosplane.daemon.serviceAccountName" . }}
  labels:
    {{- include "chaosplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: daemon
{{- end }}
