apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chaosplane.fullname" . }}-operator
  labels:
    {{- include "chaosplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
rules:
  - apiGroups:
      - chaos.chaosplane.dev
    resources:
      - chaosexperiments
      - blastradiuspolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - chaos.chaosplane.dev
    resources:
      - chaosexperiments/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - chaos.chaosplane.dev
    resources:
      - chaosexperiments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
