apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chaosplane.fullname" . }}-operator
  labels:
    {{- include "chaosplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "chaosplane.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        {{- include "chaosplane.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: operator
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chaosplane.operator.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: operator
          image: {{ include "chaosplane.operator.image" . }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            - --leader-elect
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
